version: '3.8'

services:
  mssql_primary:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_primary
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1435:1433"
    volumes:
      - mssql_primary_data:/var/opt/mssql

  mssql_replica:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_replica
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1436:1433"
    volumes:
      - mssql_replica_data:/var/opt/mssql

volumes:
  mssql_primary_data:
  mssql_replica_data:
